server:
  port: 8084

spring:
  application:
    name: watch-history-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: streamx_history
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: watch-history-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.streamx.watchhistory.model.WatchedEvent

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus