server:
  port: 8082

spring:
  application:
    name: catalog-service

  data:
    mongodb:
      host: localhost
      port: 27017
      database: streamx_catalog
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus